<a href="https://colab.research.google.com/github/nihadern/bank-closing-prediction/blob/master/ANN_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer 
import time
from sklearn.metrics import confusion_matrix

# Importing the dataset

In [6]:
dataset = pd.read_csv('Bank_Predictions.csv')
dataset.head()

Number  Customer_ID Last_Name  ...  IsActiveMember Customer_Salary Acc_Closed
0       1     15634602  Hargrave  ...               1       101348.88          1
1       2     15647311      Hill  ...               1       112542.58          0
2       3     15619304      Onio  ...               0       113931.57          1
3       4     15701354      Boni  ...               0        93826.63          0
4       5     15737888  Mitchell  ...               1        79084.10          0

[5 rows x 14 columns]

# Part 1: Data Preprocessing


In [34]:
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:, 13].values
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


## Encoding categorical data

### Encode Location


In [35]:
labelencoder_loc = LabelEncoder()
print(X[:, 1])
X[:, 1] = labelencoder_loc.fit_transform(X[:, 1])
print(X[:, 1])

['France' 'Spain' 'France' ... 'France' 'Germany' 'France']
[0 2 0 ... 0 1 0]


### Encode Gender


In [37]:
labelencoder_gender = LabelEncoder()
print(X[:, 2])
X[:, 2] = labelencoder_gender.fit_transform(X[:, 2])
print(X[:, 2])

['Female' 'Female' 'Female' ... 'Female' 'Male' 'Female']
[0 0 0 ... 0 1 0]


### One-Hot encode location




In [0]:
# location
onehotencoder = OneHotEncoder()
ct = ColumnTransformer([("locaction", onehotencoder,[1])], remainder="passthrough") 
X = ct.fit_transform(X)

## Splitting the dataset into the Training and Test sets

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = int(time.time()))

## Feature Scaling


In [0]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2: Bulding the ANN

# Import keras library and packages


In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

## Initializing the ANN


In [0]:
model = Sequential()

## Adding the input layer and the first hidden layer

In [121]:
model.add(Dense(10, activation = 'relu', input_dim =len(X[0])))

## Adding second hidden layer

In [0]:
model.add(Dense(6, activation = 'relu'))

## Adding output layer

In [0]:
model.add(Dense(1, activation = 'sigmoid'))

## Compiling the ANN


In [126]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


## Fitting the ANN to the training set

In [128]:
model.fit(X_train, y_train, 
          batch_size = 10, 
          epochs = 100,
          verbose=1,
          validation_data=(X_test, y_test))




Train on 8000 samples, validate on 2000 samples
Epoch 1/100





8000/8000 [==============================] - 2s 245us/step - loss: 0.6156 - acc: 0.7226 - val_loss: 0.5288 - val_acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.4930 - acc: 0.7964 - val_loss: 0.4699 - val_acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.4613 - acc: 0.7964 - val_loss: 0.4533 - val_acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4485 - acc: 0.7964 - val_loss: 0.4436 - val_acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 162us/step - loss: 0.4387 - acc: 0.7964 - val_loss: 0.4361 - val_acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.4307 - acc: 0.7964 - val_loss: 0.4302 - val_acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.4233 - acc: 0.7964 - val_loss: 0.4240 - v

##  Predicting the Test set results

In [129]:
THRESHOLD = 0.5
predictions = model.predict(X_test)

predictions = (predictions > THRESHOLD)
print(predictions)

[[False]
 [ True]
 [False]
 ...
 [False]
 [False]
 [False]]


## Making the confusion Matrix

In [134]:
cm = confusion_matrix(y_test, predictions)
print(cm)

[[1463  129]
 [ 191  217]]


2000